name: materials-fds-no-foot
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  - xeus-python # A Jupyter kernel for Python
  - otter-grader-base
  - pandas
  - matplotlib
  - datascience ==0.18.1
  - numpy==2.2.6     # ?
  - scipy==1.14.1   # ?
  - urllib3<2.0   # ?
  - pip: # List pure Python packages from PyPi here
    - ipyleaflet
