name: materials-fds-no-foot
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  - xeus-python # A Jupyter kernel for Python
  - pandas
  - matplotlib
  - datascience==0.18.1
  - otter-grader-base
  - numpy==2.2.6
  - scipy==1.14.1
  - xeus-r # A Jupyter kernel for R
  - xeus-cpp # A Jupyter kernel for C++
  - pip: # List pure Python packages from PyPi here
    - ipyleaflet

