name: materials-fds-no-foot
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  - xeus-python # A Jupyter kernel for Python
  - otter-grader-base
  - pandas
  - matplotlib
  - scipy
  - xeus-r # A Jupyter kernel for R
  - xeus-cpp # A Jupyter kernel for C++
  - pip: # List pure Python packages from PyPi here
    - ipyleaflet
    - datascience

